### ISSUE TITLE
Support updating APOs

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sdr-api#498]
I'm attempting to update an APO via sdr-client and I'm getting an error when trying to do so via multiple methods. I'm guessing that the problem is the fact that I'm trying to update an APO. I've successfully updated items.

Commands I've tried:

```
# post a new Cocina file (doesn't work even if cocina is unchanged)
sdr update "druid:br603yt1286" --cocina-file hydrus-apo.json --url "$SERVICE_URL_STAGE"
```

```
# try to change the APO for an APO (from the Hydrus Ur-APO to SDR Graveyard)
sdr update "druid:br603yt1286" --admin-policy "druid:hv992ry2431" --url "$SERVICE_URL_STAGE"
```

Error I receive back:
```
I, [2022-09-07T14:24:21.799080 #6339]  INFO -- : Retrieving metadata from: /v1/resources/druid:br603yt1286
D, [2022-09-07T14:24:22.396891 #6339] DEBUG -- : Starting update metadata: {"cocinaVersion":"0.75.0","type":"https://cocina.sul.stanford.edu/models/admin_policy","externalIdentifier":"druid:br603yt1286","label":"APO for teleology","version":1,"administrative":{"accessTemplate":{"view":"world","controlledDigitalLending":false,"download":"world","useAndReproductionStatement":"User agrees that, where applicable, content will not be used to identify or to otherwise infringe the privacy or confidentiality rights of individuals. Content distributed via the Stanford Digital Repository may be subject to additional license and use restrictions applied by the depositor."},"registrationWorkflow":[],"collectionsForRegistration":[],"hasAdminPolicy":"druid:hv992ry2431","hasAgreement":"druid:mc322hh4254","roles":[{"name":"hydrus-collection-manager","members":[{"type":"sunetid","identifier":"suntzu"}]},{"name":"hydrus-collection-depositor","members":[{"type":"sunetid","identifier":"suntzu"}]},{"name":"dor-apo-manager","members":[{"type":"workgroup","identifier":"sdr:developer"},{"type":"workgroup","identifier":"sdr:service-manager"},{"type":"workgroup","identifier":"sdr:metadata-staff"}]}]},"description":{"title":[{"structuredValue":[],"parallelValue":[],"groupedValue":[],"value":"APO for teleology","identifier":[],"note":[],"appliesTo":[]}],"contributor":[],"event":[],"form":[],"geographic":[],"language":[],"note":[],"identifier":[],"subject":[],"relatedResource":[],"marcEncodedData":[],"purl":"https://sul-purl-stage.stanford.edu/br603yt1286"}}
/Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-0.92.0/lib/sdr_client/deposit/unexpected_response.rb:16:in `call': There was an error with your request: {"id":"bad_request","message":"{\\"cocinaVersion\\"=>\\"0.75.0\\", \\"type\\"=>\\"https://cocina.sul.stanford.edu/models/admin_policy\\", \\"externalIdentifier\\"=>\\"druid:br603yt1286\\", \\"label\\"=>\\"APO for teleology\\", \\"version\\"=>1, \\"administrative\\"=>{\\"accessTemplate\\"=>{\\"view\\"=>\\"world\\", \\"controlledDigitalLending\\"=>false, \\"download\\"=>\\"world\\", \\"useAndReproductionStatement\\"=>\\"User agrees that, where applicable, content will not be used to identify or to otherwise infringe the privacy or confidentiality rights of individuals. Content distributed via the Stanford Digital Repository may be subject to additional license and use restrictions applied by the depositor.\\"}, \\"registrationWorkflow\\"=>[], \\"collectionsForRegistration\\"=>[], \\"hasAdminPolicy\\"=>\\"druid:hv992ry2431\\", \\"hasAgreement\\"=>\\"druid:mc322hh4254\\", \\"roles\\"=>[{\\"name\\"=>\\"hydrus-collection-manager\\", \\"members\\"=>[{\\"type\\"=>\\"sunetid\\", \\"identifier\\"=>\\"suntzu\\"}]}, {\\"name\\"=>\\"hydrus-collection-depositor\\", \\"members\\"=>[{\\"type\\"=>\\"sunetid\\", \\"identifier\\"=>\\"suntzu\\"}]}, {\\"name\\"=>\\"dor-apo-manager\\", \\"members\\"=>[{\\"type\\"=>\\"workgroup\\", \\"identifier\\"=>\\"sdr:developer\\"}, {\\"type\\"=>\\"workgroup\\", \\"identifier\\"=>\\"sdr:service-manager\\"}, {\\"type\\"=>\\"workgroup\\", \\"identifier\\"=>\\"sdr:metadata-staff\\"}]}]}, \\"description\\"=>{\\"title\\"=>[{\\"structuredValue\\"=>[], \\"parallelValue\\"=>[], \\"groupedValue\\"=>[], \\"value\\"=>\\"APO for teleology\\", \\"identifier\\"=>[], \\"note\\"=>[], \\"appliesTo\\"=>[]}], \\"contributor\\"=>[], \\"event\\"=>[], \\"form\\"=>[], \\"geographic\\"=>[], \\"language\\"=>[], \\"note\\"=>[], \\"identifier\\"=>[], \\"subject\\"=>[], \\"relatedResource\\"=>[], \\"marcEncodedData\\"=>[], \\"purl\\"=>\\"https://sul-purl-stage.stanford.edu/br603yt1286\\"}, \\"id\\"=>\\"druid:br603yt1286\\"} isn't one of in #/paths/~1v1~1resources~1{id}/put/requestBody/content/application~1json/schema"} (SdrClient::Deposit::UnexpectedResponse::BadRequest)
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-0.92.0/lib/sdr_client/deposit/update_resource.rb:27:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-0.92.0/lib/sdr_client/deposit/update_resource.rb:10:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-0.92.0/lib/sdr_client/update.rb:19:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-0.92.0/lib/sdr_client/update.rb:8:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-0.92.0/lib/sdr_client/cli.rb:77:in `update'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/gems/sdr-client-0.92.0/exe/sdr:8:in `<top (required)>'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `load'
	from /Users/bergeraj/.rvm/gems/ruby-3.0.0/bin/sdr:23:in `<main>'
```

This command worked for an item:
```
sdr update druid:bb515rw9517 --url "$SERVICE_URL_STAGE" --cocina-file item-cocina.json
```

**Comment by mjgiarlo** [comment]
@andrewjbtw This is now deployed to all envs for you to use. I don't believe this requires any changes to sdr-client, but if you find oddities or breakages, let me know!
